
main: main.cpp FA/FA.cpp IO/inputBuffer.cpp config/config.cpp dependency/jsoncpp.cpp Gram/Gram.cpp exception/Exception.cpp
	g++ main.cpp FA/FA.cpp IO/inputBuffer.cpp config/config.cpp dependency/jsoncpp.cpp Gram/Gram.cpp exception/Exception.cpp -o main -I include/
